defaults:
  - model/pi0_5@actor.model
  - hybrid_engines/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:RLINF_SFT_CONFIG}

cluster:
  num_nodes: 1
  component_placement:
    actor: "0"

runner:
  task_type: sft
  logger:
    log_path: ${oc.env:RPENT_FLYWHEEL_OUTPUT}
    project_name: rpent
    experiment_name: flywheel_pi05_sft
    logger_backends: []
  max_epochs: -1
  max_steps: 1000
  val_check_interval: -1
  save_interval: 100

data:
  train_data_paths: ${oc.env:RPENT_FLYWHEEL_DATASET}

actor:
  group_name: ActorGroup
  training_backend: fsdp
  micro_batch_size: 1
  global_batch_size: 1
  seed: 0
  model:
    model_path: ${oc.env:RPENT_FLYWHEEL_CHECKPOINT}
    is_lora: false
    openpi:
      train_expert_only: false
  fsdp_config:
    use_orig_params: false
  optim:
    lr: 7.91e-6
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-8
    weight_decay: 0.01
    clip_grad: 1.0
    lr_scheduler: constant
    lr_warmup_steps: 0
    total_training_steps: ${runner.max_steps}
