defaults:
  - env/realworld_dual_franka_tcp_rot6d@env.eval
  - _self_
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 2
  component_placement:
    env:
      node_group: dual_franka
      placement: 0
  node_groups:
    - label: dual_franka
      node_ranks: 0-1
      hardware:
        type: DualFranka
        configs:
          - left_robot_ip: "172.16.0.2"
            right_robot_ip: "172.16.0.2"
            base_camera_serials: ["141722070657"]
            base_camera_type: realsense
            left_camera_serials: ["usb-XVisio_Technology_XVisio_vSLAM_250801DR48FB26001216-video-index0"]
            left_camera_type: lumos
            right_camera_serials: ["usb-XVisio_Technology_XVisio_vSLAM_250801DR48FB26001242-video-index0"]
            right_camera_type: lumos
            left_gripper_type: robotiq
            right_gripper_type: robotiq
            left_gripper_connection: "/dev/serial/by-id/usb-FTDI_USB_TO_RS-485_DAAIR00N-if00-port0"
            right_gripper_connection: "/dev/serial/by-id/usb-FTDI_USB_TO_RS-485_DAAIT8PU-if00-port0"
            left_controller_node_rank: 0
            right_controller_node_rank: 1
            node_rank: 0

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: dual-franka-physical-agent-eval
    logger_backends: [tensorboard]

env:
  group_name: EnvGroup
  eval:
    use_spacemouse: false
    use_gello: false
    use_gello_joint: false
    keyboard_reward_wrapper: null
    main_image_key: left_wrist_0_rgb
    data_collection:
      enabled: false
    override_cfg:
      enable_camera_player: false
      task_description: dual arm physical agent task
      joint_reset_qpos:
        - [0.0, 0.0, 0.0, -1.9, 0.0, 2.0, 0.0]
        - [0.0, 0.0, 0.0, -1.9, 0.0, 2.0, 0.0]
      target_ee_pose:
        - [0.5, -0.2, 0.5, -3.14, 0.0, 0.0]
        - [0.5, 0.2, 0.5, -3.14, 0.0, 0.0]