defaults:
  - env/realworld_physical_agent_franka@env.eval
  - _self_
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 1
  component_placement:
    env:
      node_group: franka
      placement: 0
  node_groups:
    - label: franka
      node_ranks: 0
      hardware:
        type: Franka
        configs:
          - robot_ip: ROBOT_IP
            node_rank: 0

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: franka-physical-agent-eval
    logger_backends: [tensorboard]

env:
  group_name: EnvGroup
  eval:
    use_spacemouse: false
    keyboard_reward_wrapper: null
    main_image_key: wrist_1
    data_collection:
      enabled: false